### ISSUE TITLE
Traits Data

### ISSUE THREAD

**Issue by TanyaS08** [Plant-Functional-Trait-Course/pftc3_punaproject_pftc5#3]
Running tab of issues picked up on a second pass of the traits data - see also PF #1 I'm going to structure them as comments as they come up

**Comment by PaulESantos** [comment]
> 1. **Treatments  names (and then some):**
> 
> For PFTC5: There are "C", "NB", and "B" plots (and the "OFF PLOTS" that I am assuming are Sean's) We should only have two categories if I'm correct "C" and I _think_ "BB"/NB??
> 
> "NB" should be BB (PFTC3 uses BB and Puna and PFTC5 use NB) - we need to pick one
> 
> ![Screenshot 2021-02-27 at 16 48 25 (2)](https://user-images.githubusercontent.com/61696728/109390799-53636480-791c-11eb-84ee-6c56cc987662.png)

the BB code was used in PFTC3 for PIL (PillcoGrande plots) a special treatment and its different from NB

**Comment by PaulESantos** [comment]
> 🚩 Sample ID AZJ4672 (from Puna Project) has a 0 value for dry mass (plausible as might be too light for resolution of scale) but this does spit out a Inf for things like SLA and ldmc. Again not an **issue** but might be worth correcting to be NA to make the dataset more user friendly?

If you find more missing dry mass is because the leaves are too light for the resolution of the scale.

**Comment by TanyaS08** [comment]
I'm just adding this in here regarding the Burt treatments - if there are indeed a NB and a BB treatment then we should just confirm how we are treating PFTC 5 - that is will these sites then be B? If yes we need to do a scan of the data documentation because I think we were calling it BB

**Comment by TanyaS08** [comment]
Okay let me wrap my head around this:
BB = special burn
NB = burnt for the first time (as far as we know)
B = burnt recently 
C = unburnt - BUT is this unburnt for e.g. 20 years or is it has never been burnt (as far as we know)

**Comment by audhalbritter** [comment]
can we close this issue @TanyaS08 ?

**Comment by TanyaS08** [comment]
I think now that we have the burn data sorted yes - I was using it as my quick reference tool when questioning things
